### ISSUE TITLE
Printer produces malformed EDN on browsable literals

### ISSUE THREAD

**Issue by zampino** [cgrand/unrepl#51]
I might be using the `Navigable` protocol wrong, but I think unrepl printer has some issues when printing `'unrepl/browsable` literals. Take the following simple example (our orginal usecase is using datomic.query.EntityMap classes with the same implementation)

```clj
(ns datanav
  (:require [clojure.datafy :as d]
            [clojure.core.protocols :as p]))

(defrecord DN [a b]

  p/Datafiable
  (datafy [this]
    (into {} this))

  p/Navigable
  (nav [this k v]
    (d/datafy v)))

```
 evaluating `(DN. 1 2)` in an unrepl session gives a browsable tag with the "standard" representation and an elision to the datafied value:
```clj
[:eval #unrepl/browsable [#datanav.DN {:a 1, :b 2} #unrepl/... {:get (unrepl.repl$uehLEhDeEXfvTWuBD5h6Hh09nOw/fetch :G__793)}] 7]
```
now following the elision 
```clj
(unrepl.repl$uehLEhDeEXfvTWuBD5h6Hh09nOw/fetch :G__793)
```
I will find the result of `unrepl.printer/browsify` and that is
```clj
[:eval (({:a # [nil #unrepl/... {:get (unrepl.repl$uehLEhDeEXfvTWuBD5h6Hh09nOw/fetch :G__798)}, :b # [nil #unrepl/... {:get (unrepl.repl$uehLEhDeEXfvTWuBD5h6Hh09nOw/fetch :G__799)}})) 9]
```
but this EDN cannot be read, the reader will throw a _No dispatch macro_ for the `nil` tag in the value to the `:a` field.

The reason for the `nil` reader tags might reside around this printer code
https://github.com/Unrepl/unrepl/blob/37954c3015d93c0d71df26c141efd9a9347003cc/src/unrepl/printer.clj#L363-L369
while rebinding `x` to the first element of `(:form x)`, can we still assume that `x` is again a tagged literal? Is it intentional the missing closing `]` here?

Also tried the above example in [iClojure](https://github.com/HCADatalab/IClojure#try-it) and the same behaviour is reproducible. In fact the reader in the Jupyter server complains with:

```
SHELL
{:idents (#object["[B" 0x6d784764 "[B@6d784764"]), :delimiter "<IDS|MSG>", :signature "ea5b950836e66a67b2ad85845d6aee4a819f22b354a03506ac9fc594ffcbbdc3", :header {:session "759ae8f9-2f32-4c97-a2df-bbc91964aa0f", :version "5.2", :username "", :date "2019-05-27T13:10:34.140090Z", :msg_type "comm_msg", :msg_id "a6bbe3b1-4aef-461e-87dd-c8b5840eaf41"}, :parent-header {}, :content {:data {:elision-id "(unrepl.repl$p8QhJwTpu2S19yqqZbyXWLOYcI8/fetch :G__840)"}, :comm_id "ca4c3a3c-6e6a-450c-9695-c0355b48d512"}} :comm ["expansion" #object[clojure.core.async.impl.channels.ManyToManyChannel 0x59fe0512 "clojure.core.async.impl.channels.ManyToManyChannel@59fe0512"]]
elision-id "(unrepl.repl$p8QhJwTpu2S19yqqZbyXWLOYcI8/fetch :G__840)"
going-to-resolve
Exception in thread "async-thread-macro-10" java.lang.RuntimeException: No dispatch macro for:  
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:552)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$ListReader.invoke(EdnReader.java:654)

```

@cgrand any insight or hints to a solution here would be really helpful. Let me thank you again for the amazing work.

**Comment by zampino** [comment]
@cgrand this is great, thank you for fixing this!
